Create serializer for ride
cuappdev/scoop-backend pull request #10
Opened 2022-04-21 22:34 UTC by katesliang

## Overview

Create serializer for ride

## Changes Made

- Create serializer for ride
- Create serialize for path

## Test Coverage

Tested when creating and getting a ride (in next PR)

## Next Steps

Create routes for creating and getting a ride

2022-04-21 23:12 UTC, alanna-zhou requested changes
same comment as other PR

2022-04-21 23:12 UTC, alanna-zhou commented on src/ride/serializers.py
> +
same comment as the other PR

2022-04-22 15:10 UTC, alanna-zhou approved these changes
GOAT.

such a fast learner, very quirky.

2022-04-23 02:10 UTC, kidzegeye approved these changes
LGTM

2022-04-23 16:52 UTC, chalo2000 approved these changes
LGTM, I am very happy with the way you are splitting apart these PRs to make them more readable for us :)

2022-04-23 16:55 UTC, noah-solomon approved these changes
valid valid valid

2022-04-23 16:55 UTC, noah-solomon commented on src/path/serializers.py
> +            "end_location_name",
loving the specificity 🤩

2022-04-23 18:36 UTC, merged