Implement update ride
cuappdev/scoop-backend pull request #12
Opened 2022-04-29 21:33 UTC by katesliang

## Overview

Implement update ride

## Changes Made

- Created route for updating ride 
- Refactored URLS and views for creating, updating, and getting ride(s)

## Test Coverage

Manual testing via Postman

## Update Ride
### /api/rides/<int:ride_id> - POST
_**IMPORTANT**: To remove a driver from ride, pass in null value for rider. To update riders, pass in a list of ALL the new rider ids (even if they have been previously added)._

Example request body:
``` 
{
    "driver": 18,
    "riders": [19]
}
```
Example response:
```
{
    "id": 29,
    "creator": {
        "id": 18,
        "netid": "test93",
        "first_name": "Tester",
        "last_name": "Test",
        "profile_pic_url": "https://appdev-upload.nyc3.digitaloceanspaces.com/scoop/qs4c2xji.png",
        "grade": "2023",
        "pronouns": null
    },
    "max_travelers": 4,
    "min_travelers": 1,
    "departure_datetime": "2020-03-27T00:00:00Z",
    "description": "",
    "driver": null,
    "is_flexible": true,
    "riders": [],
    "estimated_cost": null,
    "path": {
        "id": 29,
        "start_location_place_id": "test",
        "start_location_name": "test place name",
        "end_location_place_id": "test end",
        "end_location_name": "test end place name"
    },
    "type": "rideshare"
}
```

2022-04-29 23:00 UTC, alanna-zhou requested changes
nice job!! ur churning out these codes very nicely.

just some comments

2022-04-29 23:00 UTC, alanna-zhou commented on src/api/urls.py
> +    path("rides/", RidesView.as_view(), name="all_rides"),
much better

2022-04-29 23:00 UTC, alanna-zhou commented on src/ride/views.py
> +            return failure_response("Ride does not exist")
i think all failure responses should be handled inside the controller..?

2022-04-29 23:00 UTC, alanna-zhou commented on src/api/utils.py
> +        existing_set.set(new_objects)
this is a bit strange imo. i've never seen this kind of code before and i think it's too convoluted. in general, it's just ugly to be passing around class names.. is there a reason why you can't just do `ride.riders.set([rider for rider in Rider.objects.filter()])`.. below? it's a one liner code

2022-04-30 01:32 UTC, katesliang commented on src/api/utils.py
> +        existing_set.set(new_objects)
ah i took this helper function from pear LOL but i think this is cleaner

2022-04-30 01:43 UTC, alanna-zhou commented on src/api/utils.py
> +        existing_set.set(new_objects)
interesting... now that you mention it... it does look like something @chalo2000 or @noah-solomon would write lOLOL

2022-04-30 04:45 UTC, alanna-zhou approved these changes
just nits but other than that ur amazing

let gonzalo review before merging

2022-04-30 04:45 UTC, alanna-zhou commented on src/ride/controllers/update_ride_controller.py
> +            return failure_response(f"Invalid rider passed in: {e}")
except exception as e is bad style -- we should catch for a specific error

2022-04-30 04:45 UTC, alanna-zhou commented on src/ride/controllers/update_ride_controller.py
> +        # Get the model
you canremove this comment

2022-04-30 04:45 UTC, alanna-zhou commented on src/ride/views.py
> +        return UpdateRideController(request, data, self.serializer_class, id).process()
nice

2022-05-01 17:43 UTC, kidzegeye approved these changes
LGTM

2022-05-01 18:32 UTC, noah-solomon approved these changes
LVTM (looks valid to me)

2022-05-01 18:50 UTC, alanna-zhou commented
> LVTM (looks valid to me)

omg ur making this a thing now

2022-05-04 01:32 UTC, chalo2000 approved these changes
Address my comments and then you can merge.

2022-05-04 01:32 UTC, chalo2000 commented on src/api/urls.py
> +    path("rides/", RidesView.as_view(), name="all_rides"),
now that you renamed `AllRidesView` to `RidesView` can we also name `all_rides` to `rides` thx

2022-05-04 01:32 UTC, chalo2000 commented on src/ride/controllers/update_ride_controller.py
> +        try:
and if `rider_ids` is None because I didn't need to update it when I called this route?

2022-05-04 01:32 UTC, chalo2000 commented on src/ride/controllers/update_ride_controller.py
> +        ride = Ride.objects.get(path_id=self._id)
why is the ID I am passing into a ride endpoint being used to get a ride based on the path_id? I understand that it's a one-to-one relationship but semantically it makes sense that you get the ride based on it's own ID and then you can extract the path from it. Worst case scenario, the IDs for rides and paths do not match (for whatever reason) and then your update ride controller starts updating the wrong ride.

2022-05-04 02:19 UTC, merged