[1/x] Create request model
cuappdev/scoop-backend pull request #15
Opened 2022-09-22 01:27 UTC by katesliang

## Overview

Implement request to join ride model

## Changes Made

- Created request model 

## Test Coverage

N/A

## Next Steps

Implementing request serializer in next PR

2022-09-27 01:59 UTC, chalo2000 requested changes
Can you explain what you did to change the request model? Also, why am I seeing changes here from a previous PR?

2022-09-27 01:59 UTC, chalo2000 commented on src/ride/controllers/create_ride_controller.py
> +        path_exists = Path.objects.filter(
this was in the previous PR?

2022-09-29 17:05 UTC, chalo2000 requested changes
PR is bare, we're creating the models and need to understand what the bigger picture is. To me it is clear why an approvee/approver can have many requests and it also makes sense why a ride may have many requests but I don't know how this works; will there be a way to handle requests for a ride when it already happened, will the requests be deleted. I need more context somewhere and if it's not appropriate to put all the details on this PR (which I don't think it would since this is just creating models and nothing to do with functionality) then I need some issue that describes in a little more depth how requests comes into play.

2022-09-29 17:05 UTC, chalo2000 commented on src/request/models.py
> +    ride = models.ForeignKey(Ride, on_delete=models.CASCADE)
many requests belong to one ride? how does this work

2022-10-02 20:55 UTC, katesliang commented on src/request/models.py
> +    ride = models.ForeignKey(Ride, on_delete=models.CASCADE)
ya, each request can have many requests. created an issue #20 that explains the process further.

2022-10-12 21:21 UTC, chalo2000 approved these changes
Add under the Related PRs section the issue you created (#20) and then you can merge

2022-10-12 21:21 UTC, joycrwu approved these changes
cool

2022-10-12 21:24 UTC, merged