Start prompt app | Prompts [1/X]
cuappdev/scoop-backend pull request #22
Opened 2022-10-30 05:35 UTC by joycrwu

## Overview

Started a new Django app for prompts. 

## Changes Made

Filled out a couple of views -- including getting all prompts, creating a prompt, getting a specific prompt, updating a specific prompt, deleting a specific prompt. 

## Test Coverage

N/A -- started a new Django app

## Next Steps (delete if not applicable)

Write out the controllers for the prompts nd update the prompts to reflect what kind of information Django is actually seeking from its users.

2022-10-31 20:56 UTC, katesliang requested changes
good start to prompts! code is slay 

just a few nits: 
- could you create an issue (like #20) that summarizes what you plan to do with this stack?
- could you summarize the new views that you created in your PR (like the endpoints, sample request bodies and responses)?
- it may be better to delete the views that have the controllers for now and then add it in later as we create it so we don't have any unresolved imports

2022-11-02 03:26 UTC, chalo2000 approved these changes
+1 on all of Kate's good points, create issues to describe what you're going to do, have better PR descriptions, and push code that compiles! after addressing her comments you can merge this in.

2022-11-11 01:35 UTC, joycrwu commented
> good start to prompts! code is slay
> 
> just a few nits:
> 
> * could you create an issue (like #20) that summarizes what you plan to do with this stack?
> * could you summarize the new views that you created in your PR (like the endpoints, sample request bodies and responses)?
> * it may be better to delete the views that have the controllers for now and then add it in later as we create it so we don't have any unresolved imports

2022-11-11 01:37 UTC, joycrwu commented
@katesliang changes made! also made an issue and committed code that the views can reference in the controller now

2022-11-13 22:30 UTC, katesliang approved these changes
nice changes!! pls address my comments before merging~~ 

also when you merge, remember to do "squash and merge" so that the commit history in master is cleaner

pr looks super profesh now

2022-11-13 22:30 UTC, katesliang commented on src/prompts/views.py
> +# from .controllers.update_prompt_controller import UpdatePromptController
delete comments

2022-11-13 22:30 UTC, katesliang commented on src/api/urls.py
> +    path("prompts/", PromptsView.as_view(), name="prompts")
nit: could you create separate urls.py for prompts?

2022-11-13 22:30 UTC, katesliang commented on src/prompts/views.py
> +# from .controllers.update_prompt_controller import UpdatePromptController
remember to reinstall the pre commit hooks on your new laptop so that if formats everything nicely for you before committing !

2022-11-13 22:30 UTC, katesliang commented on src/api/urls.py
> +    path("prompts/", PromptsView.as_view(), name="prompts")
similar to what is done in #17

2022-11-15 17:55 UTC, chalo2000 approved these changes
LGTM

2022-11-15 17:55 UTC, chalo2000 commented on src/prompts/controllers/create_prompt_controller.py
> +        label = self._data.get("question_placeholder")
why label and not placeholder?

2022-11-15 17:55 UTC, chalo2000 commented on src/prompts/views.py
> +# class PromptView(generics.GenericAPIView):
delete comments

2022-11-16 23:23 UTC, merged