Implement Google Places Search
cuappdev/scoop-backend pull request #32
Opened 2023-03-20 19:47 UTC by katesliang

## Overview

Modify existing search algorithm to use Google Places

## Changes Made

- Include nearby rides within 5 mi of the search query's start and end location
- Sort final results by ride's total proximity from query's start and end location and difference in departure time

## Test Coverage

Manual testing via Postman

## Related PRs or Issues

Closes #28 

## /api/search/

Sample Request Body:
```
{
    "departure_datetime": "2020-03-27",
    "start_location_place_id": "ChIJndqRYRqC0IkR9J8bgk3mDvU",
    "end_location_place_id": "ChIJ94iv4IKB0IkRdM5upWgn5Qo"
}
```

Sample Request Response:
```
[
    {
        "id": 3,
        "creator": {
            "id": 1,
            "netid": "ksl67",
            "first_name": "Kate",
            "last_name": "Liang",
            "profile_pic_url": null,
            "grade": "2024",
            "pronouns": "she/her"
        },
        "max_travelers": 4,
        "min_travelers": 1,
        "departure_datetime": "2020-03-27T00:00:00Z",
        "description": "",
        "driver": null,
        "is_flexible": true,
        "riders": [],
        "estimated_cost": null,
        "path": {
            "id": 2,
            "start_location_place_id": "ChIJ94iv4IKB0IkRdM5upWgn5Qo",
            "start_location_name": "cornell",
            "end_location_place_id": "ChIJ94iv4IKB0IkRdM5upWgn5Qo",
            "end_location_name": "syracuse"
        },
        "type": "rideshare"
    }
]
```

2023-03-22 21:51 UTC, snajima requested changes

2023-03-22 21:51 UTC, snajima commented on src/ride/controllers/search_ride_controller.py
> +                and geopy.distance.geodesic(path_end_coords, end_coords).km < 5
change this to also miles and allow frontend to specify number of miles

2023-03-23 00:10 UTC, snajima approved these changes
slayy ~ !

2023-03-23 15:06 UTC, joycrwu approved these changes
lgtm

2023-03-23 17:59 UTC, merged